### ISSUE TITLE
大佬能否支持下win7？

### ISSUE THREAD

**Issue by drw2005** [aiyakuaile/easy_tv_live#4]
发现win7下运行不了。

**Comment by aiyakuaile** [comment]
我没有windows电脑，无法确定什么原因，按理说只要是64位的系统应该都能运行才对

**Comment by drw2005** [comment]
![QQ截图20240816145956](https://github.com/user-attachments/assets/8b1f3de6-075c-4f32-8326-9db2949f2e92)

提示这个

**Comment by aiyakuaile** [comment]
![image](https://github.com/user-attachments/assets/af8e9930-137a-4082-8410-4a379a8cbd06)

查了下官方的信息，确实不支持win7了

**Comment by drw2005** [comment]
有没有可能支持一下呢，WIN7用户还是不少的。

**Comment by aiyakuaile** [comment]
没有，这个还是跟着官方走
