### ISSUE TITLE
电视版添加m3u8直播源

### ISSUE THREAD

**Issue by lijingbo666** [aiyakuaile/easy_tv_live#5]
如题，扫码只能推送链接怎么添加m3u8的直播源文件呢

**Comment by aiyakuaile** [comment]
目前还不支持直接添加，后续可能会考虑，现在的话只能先上传到类似 Gitee码云的地方，使用链接订阅

**Comment by lijingbo666** [comment]
> 目前还不支持直接添加，后续可能会考虑，现在的话只能先上传到类似 Gitee码云的地方，使用链接订阅

感谢回答，请问有类似的教程吗

**Comment by aiyakuaile** [comment]
在gitee上新建一个仓库，把文件上传上去后，复制原始文件链接

**Comment by lijingbo666** [comment]
> 在gitee上新建一个仓库，把文件上传上去后，复制原始文件链接

好的，感谢作者
