### ISSUE TITLE
可不可以支持更改字体啊

### ISSUE THREAD

**Issue by shermans** [aiyakuaile/easy_tv_live#6]
大佬你好。
我安装的是TV版2.6.0
喜欢这种极简风格

能不能支持换字体啊。
正楷确实好看。 但是不容易辨认。
所以各大操作系统，几乎所有网页，阅读APP默认字体都不是正楷。
因为真的不方便快速识别。认字慢。
方便快速识别又好看的字体应该是苹果平方，谷歌思源，方正兰亭，小米兰亭，微软雅黑等等。
这些也是阅读APP用的多的字体。特别是微软雅黑，所有人都比较习惯雅黑。

**Comment by shermans** [comment]
感谢大佬为大家提供了这么方便好用的APP。
祝你每更一版就帅一分，长一毫米。

**Comment by aiyakuaile** [comment]
v2.6.6版本开始支持调整字体和字体大小
