### ISSUE TITLE
无法自动识别分类

### ISSUE THREAD

**Issue by syq0806** [aiyakuaile/easy_tv_live#7]
导入m3u格式的源，无法自动识别分类，导入tvbox之类的壳子没问题，格式为：#EXTINF:-1,tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://epg.v1.mk/logo/CCTV1.png" group-title="央视",CCTV-1
http://192.168.1.32:35455/itv/00000000000000000.m3u8?cdn=wasusyt
貌似是m3u8后面如果带了?cdn=wasusyt，就无法正常识别分类，不知道作者能不能兼容一下，软件很好用！

**Comment by aiyakuaile** [comment]
@syq0806
m3u的格式标准格式是：
```
#EXTM3U
#EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" group-title="央视",CCTV-1 综合
.......
```
请先确认第一行包含`#EXTM3U`吗？

**Comment by aiyakuaile** [comment]
我是通过判断第一行是不是以`#EXTM3U`开头的，来区分本次添加的源的类型，区分.m3u和.txt的

**Comment by syq0806** [comment]
> @syq0806 m3u的格式标准格式是：
> 
> ```
> #EXTM3U
> #EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" group-title="央视",CCTV-1 综合
> .......
> ```
> 
> 请先确认第一行包含`#EXTM3U`吗？

``#EXTM3U x-tvg-url="https://epg.v1.mk/fy.xml"
#EXTINF:-1 tvg-name="4K60PSDR-H264-AAC测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/tg.jpg" group-title="4K频道",4K60PSDR-H264-AAC测试
https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/sdr4kvideo/index.m3u8
#EXTINF:-1 tvg-name="4K60PHLG-HEVC-EAC3测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/tg.jpg" group-title="4K频道",4K60PHLG-HEVC-EAC3测试
https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/hlg4kvideo/index.m3u8
#EXTINF:-1,tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://epg.v1.mk/logo/CCTV1.png" group-title="央视",cctv1-高码
http://192.168.1.2:35455/ysptp/cctv1.m3u8
#EXTINF:-1,tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://epg.v1.mk/logo/CCTV1.png" group-title="央视",CCTV-1
http://192.168.1.2:35455/itv/6000000001000029752.m3u8?cdn=wasusyt
#EXTINF:-1,tvg-id="cctv1" tvg-name="cctv1" tvg-logo="https://epg.v1.mk/logo/cctv1.png" group-title="央视",CCTV-1-50-FPS
http://192.168.1.2:35455/itv/5000000004000002226.m3u8?cdn=bestzb``
这个是我本地docker搭建导出来的源里面的截取，只有前面2个4K频道源能正常识别分类为4K频道，央视及后面的分类均无法识别分类，归为默认，我看了下唯一的区别就是m3u8后面带不带?cdn=wasusyt。

**Comment by aiyakuaile** [comment]
> > @syq0806 m3u的格式标准格式是：
> > ```
> > #EXTM3U
> > #EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" group-title="央视",CCTV-1 综合
> > .......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请先确认第一行包含`#EXTM3U`吗？
> 
> ```
> #EXTM3U x-tvg-url="https://epg.v1.mk/fy.xml"
> #EXTINF:-1 tvg-name="4K60PSDR-H264-AAC测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/tg.jpg" group-title="4K频道",4K60PSDR-H264-AAC测试
> https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/sdr4kvideo/index.m3u8
> #EXTINF:-1 tvg-name="4K60PHLG-HEVC-EAC3测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/tg.jpg" group-title="4K频道",4K60PHLG-HEVC-EAC3测试
> https://cdn.jsdelivr.net/gh/feiyangdigital/testvideo/hlg4kvideo/index.m3u8
> #EXTINF:-1,tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://epg.v1.mk/logo/CCTV1.png" group-title="央视",cctv1-高码
> http://192.168.1.2:35455/ysptp/cctv1.m3u8
> #EXTINF:-1,tvg-id="CCTV1" tvg-name="CCTV1" tvg-logo="https://epg.v1.mk/logo/CCTV1.png" group-title="央视",CCTV-1
> http://192.168.1.2:35455/itv/6000000001000029752.m3u8?cdn=wasusyt
> #EXTINF:-1,tvg-id="cctv1" tvg-name="cctv1" tvg-logo="https://epg.v1.mk/logo/cctv1.png" group-title="央视",CCTV-1-50-FPS
> http://192.168.1.2:35455/itv/5000000004000002226.m3u8?cdn=bestzb
> ```
> 
> 这个是我本地docker搭建导出来的源里面的截取，只有前面2个4K频道源能正常识别分类为4K频道，央视及后面的分类均无法识别分类，归为默认，我看了下唯一的区别就是m3u8后面带不带?cdn=wasusyt。

```
#EXTINF:-1,tvg-id="CCTV1"
```
前面两个是对的，从CCTV1开始，#EXTINF:-1和tvg-id="CCTV1"多了个逗号分割，实际应该是空格才对，把逗号去掉换成空格分割再试试
