### ISSUE TITLE
UI颜色不易分辨

### ISSUE THREAD

**Issue by qqqwqk** [aiyakuaile/easy_tv_live#8]
![PXL_20240907_105850989 MP](https://github.com/user-attachments/assets/66384c56-11b8-495c-ba93-bc9cf05a6c80)
tv版 光标选中的目标是否可以换一种更突出的颜色

**Comment by aiyakuaile** [comment]
@qqqwqk v2.7.3版本对此做了视效增强，快去下载吧！
